use_frameworks!

platform :ios, '9.0'

target 'DCDemoBase_Example' do
  pod 'DCDemoBase', :path => '../'

  target 'DCDemoBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
